server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
  application:
    name: learning-server
  # 数据库相关配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://117.72.76.36:3306/scraper?useUnicode=true&autoReconnect=true&failOverReadOnly=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    hikari:
      connection-timeout: 60000
      minimum-idle: 5
      maximum-pool-size: 200
      idle-timeout: 300000
      max-lifetime: 1200000